name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron : 30 02 * * * # 8 am IST Every day
    - cron : 00 14 * * * # 730 pm IST Every day
    - cron : 00 06 * * 1-5 # 1130 am IST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Install Nodejs and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Install Newman and Html-extra globally
        run: | 
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with newman
        run: |
             newman run 'Inwarranty-flow Collection.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra


      - name: Archive the newman report
        if: always() # ensure that this step works irrespective of the passing or failure of previous step
        uses: actions/download-artifact@v4.3.0
        with:
          name: Newman Report
          path: newman/*.html

        
        














  
